// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ztOZk2IGkDntnBIZgJGfycdi3JrYyMI',
    appId: '1:473132844745:web:7d8f5d9773ba687141ef18',
    messagingSenderId: '473132844745',
    projectId: 'trip-planner-ec182',
    authDomain: 'trip-planner-ec182.firebaseapp.com',
    storageBucket: 'trip-planner-ec182.firebasestorage.app',
    measurementId: 'G-Y5RDHQGE8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5bhIbpxQzUwVJmWO5ngFi-df5Db4NHxQ',
    appId: '1:473132844745:android:896b523927ff263041ef18',
    messagingSenderId: '473132844745',
    projectId: 'trip-planner-ec182',
    storageBucket: 'trip-planner-ec182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIDDLDHsVXEVfkjLR_8m1LPZpevj5iZoA',
    appId: '1:473132844745:ios:24b8382388abb10341ef18',
    messagingSenderId: '473132844745',
    projectId: 'trip-planner-ec182',
    storageBucket: 'trip-planner-ec182.firebasestorage.app',
    iosBundleId: 'tarumt.edu.my.wandry',
  );
}
